print("Obliczam funkcje kwadratowa.")
print("Podaj: a")
a = int(input())
print("Podaj: b")
b = int(input())
print("Podaj: c")
c = int(input())
print("Podaj: x")
x = int(input())
y = (a * x**2 + b * x + c)
print("Y wynosi {} dla x = {}" .format(y, x))
